import{NextResponse}from"next/server";import{and,eq}from"drizzle-orm";import{currentUser}from"@/lib/current-user";import{getDb}from"@/lib/db";import{settlements,users}from"@/db/schema";
const API="https://api.ramphub.io/api/developer",BUFFER_USD=1;
const num=(...xs:any[])=>{for(const x of xs){const n=Number(x);if(Number.isFinite(n)&&n>0)return n}return 0};
function parsed(q:any,fiat:number){const b=q?.bestQuote||q?.quote||q?.data?.bestQuote||q?.data||q||{};const token=num(b.tokenAmount,b.cryptoAmount,b.amountOut,b.outputAmount,b.receiveAmount,b.amount,q?.tokenAmount,q?.cryptoAmount);const rate=num(b.rate,b.bestRate,b.exchangeRate,q?.bestRateUsed,q?.rate);const feeFiat=num(b.fee,b.fees?.total,b.totalFee,b.providerFee,b.feeAmount,q?.fee);return{token,rate,feeFiat,fiat:num(b.fiatAmount,q?.fiatAmount,fiat)||fiat,provider:b.provider||b.selectedProvider||q?.selectedProvider||null}}
async function ask(key:string,currency:string,fiat:number){const r=await fetch(API+"/quotes",{method:"POST",headers:{"x-api-key":key,"Content-Type":"application/json"},body:JSON.stringify({side:"buy",fiatAmount:Number(fiat.toFixed(2)),fiatCurrency:currency,asset:"USDC",chain:"base"})});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error((d as any).message||"No RampHub quote is available");return d}
export async function POST(req:Request){try{const u=await currentUser(),key=process.env.RAMPHUB_API_KEY;if(!key)throw new Error("RampHub is not configured yet");const{settlementId,fiatCurrency}=await req.json(),db=getDb();const[s]=await db.select().from(settlements).where(and(eq(settlements.id,String(settlementId)),eq(settlements.fromUserId,u.id))).limit(1);if(!s||s.arcTxHash)throw new Error("Settlement is not available");const[to]=await db.select().from(users).where(eq(users.id,s.toUserId)).limit(1);if(!to?.walletAddress)throw new Error("Recipient wallet is not ready");const currency=String(fiatCurrency||"NGN").toUpperCase(),settlement=Number(s.amountUsdc),target=settlement+BUFFER_USD;
let fiat=currency==="NGN"?target*1700:target*150;let data:any=null,p:any=null;
for(let i=0;i<4;i++){data=await ask(key,currency,fiat);p=parsed(data,fiat);if(p.token>0){if(p.token>=target*.999)break;fiat=fiat*(target/p.token)*1.002}else if(p.rate>0){fiat=target*p.rate+p.feeFiat;break}else throw new Error("RampHub returned a quote, but Tab could not read its USDC output. Please retry after the quote adapter is updated.")}
data=await ask(key,currency,fiat);p=parsed(data,fiat);const output=p.token||((p.fiat-p.feeFiat)/(p.rate||1));if(!Number.isFinite(output)||output<target*.995)throw new Error("RampHub quote does not cover the settlement and safety buffer");
return NextResponse.json({quote:data,plan:{settlementUsdc:settlement,safetyBufferUsd:BUFFER_USD,targetUsdc:target,estimatedRampHubFeeFiat:p.feeFiat,estimatedPrivyRouteFeeUsd:null,fiatAmount:p.fiat,estimatedUsdcOut:output,provider:p.provider},settlement:{id:s.id,amountUsdc:s.amountUsdc,toName:to.name,toWallet:to.walletAddress},fiatCurrency:currency,note:"Privy Base-to-Arc executable route fees are not yet available to this integration; Tab will not invent them."})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to get quote"},{status:400})}}