"use client";
import{useState}from"react";
type Transfer={id:string;state:"queued"|"sending"|"completed"|"failed"|"under_review";amount:string;token:string;chain:string;tx_hash:string|null};
type Props={getAccessToken:()=>Promise<string|null>;onClose:()=>void;onComplete?:()=>void};
export function MinisendSend({getAccessToken,onClose,onComplete}:Props){
 const[email,setEmail]=useState(""),[amount,setAmount]=useState(""),[chain,setChain]=useState("BASE"),[token,setToken]=useState<"USDC"|"USDT">("USDC"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[transfer,setTransfer]=useState<Transfer|null>(null),[idempotencyKey]=useState(()=>crypto.randomUUID());
 async function headers(json=false):Promise<Record<string,string>>{const t=await getAccessToken();if(!t)throw new Error("Your session expired. Sign in again.");return json?{Authorization:"Bearer "+t,"Content-Type":"application/json"}:{Authorization:"Bearer "+t}}
 async function send(){setError("");const n=Number(amount);if(!Number.isFinite(n)||n<=0)return setError("Enter a valid amount.");setBusy(true);try{const r=await fetch("/api/wallet/minisend/transfers",{method:"POST",headers:await headers(true),body:JSON.stringify({toEmail:email.trim(),amount:n,chain,token,idempotencyKey})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Transfer failed");setTransfer(j.transfer as Transfer)}catch(e){setError(e instanceof Error?e.message:"Transfer failed")}finally{setBusy(false)}}
 async function refresh(){if(!transfer)return;setBusy(true);setError("");try{const r=await fetch("/api/wallet/minisend/transfers?id="+encodeURIComponent(transfer.id),{headers:await headers()}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not check transfer");setTransfer(j.transfer as Transfer);if(j.transfer?.state==="completed")onComplete?.()}catch(e){setError(e instanceof Error?e.message:"Could not check transfer")}finally{setBusy(false)}}
 const minimum=chain==="ETH"?20:chain==="AVAX"?0.5:0.1;
 return <div className="walletModalOverlay" onClick={onClose}><section className="walletModal" onClick={e=>e.stopPropagation()}><div className="walletModalHead"><div><span>Tab Wallet</span><h2>Send to a Tab user</h2></div><button aria-label="Close" onClick={onClose}>×</button></div>{transfer?<div className="walletRouteDetail"><b>{transfer.state==="completed"?"Transfer completed ✓":transfer.state==="failed"?"Transfer failed":transfer.state==="under_review"?"Transfer under review":"Transfer submitted"}</b><p>{transfer.amount} {transfer.token} on {transfer.chain}</p><div className="baseFundingDisclosure"><b>Status: {transfer.state.replaceAll("_"," ")}</b><small>{transfer.state==="failed"?"Nothing moved. The funds remain in your wallet.":transfer.state==="under_review"?"MiniSend is checking the outcome. Do not retry this payment yet.":transfer.tx_hash||"Waiting for the on-chain transaction."}</small></div>{transfer.tx_hash&&<code>{transfer.tx_hash}</code>}{transfer.state!=="completed"&&transfer.state!=="failed"&&<button className="walletRoutePrimary" disabled={busy} onClick={refresh}>{busy?"Checking…":"Check status"}</button>}</div>:<div className="walletRouteDetail"><p>This is a real on-chain transfer between two Tab MiniSend wallets.</p><label>Recipient Tab email<input type="email" autoCapitalize="off" autoCorrect="off" value={email} onChange={e=>setEmail(e.target.value)} placeholder="friend@example.com"/></label><label>Network<select value={chain} onChange={e=>setChain(e.target.value)}><option value="BASE">Base</option><option value="ARC">Arc</option><option value="ARB">Arbitrum</option><option value="OP">Optimism</option><option value="MATIC">Polygon</option><option value="AVAX">Avalanche</option><option value="ETH">Ethereum</option></select></label><label>Token<select value={token} onChange={e=>setToken(e.target.value as "USDC"|"USDT")}><option value="USDC">USDC</option><option value="USDT">USDT</option></select></label><label>Amount<input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder={String(minimum)}/><small>Minimum on this network: {minimum} {token}</small></label><button className="walletRoutePrimary" disabled={busy} onClick={send}>{busy?"Submitting…":"Confirm real transfer"}</button><small>MiniSend must have the transfer scope enabled for Tab's Wallet API key.</small></div>}{error&&<p className="error">{error}</p>}</section></div>
}
