"use client";
import{useEffect,useState}from"react";
type Bank={code?:string;institution?:string;name?:string;bank_name?:string};
type Quote={amount_ngn:number;amount_usdc:number};
type PaymentInstructions={bank_name:string;account_number:string;account_name:string;amount:string;currency:string;expires_at:string};
type Order={orderId:string;status:string;amountUsdc?:number;paymentInstructions?:PaymentInstructions|null;refundAccount?:{institution?:string;account_number?:string;account_name?:string}|null;releaseTxHash?:string|null;failureReason?:string|null};
type Props={getAccessToken:()=>Promise<string|null>;walletReady:boolean;onWalletNeeded:()=>void|Promise<void>};
export function NgnFunding({getAccessToken,walletReady,onWalletNeeded}:Props){
 const[banks,setBanks]=useState<Bank[]>([]),[amount,setAmount]=useState(""),[bank,setBank]=useState(""),[account,setAccount]=useState(""),[quote,setQuote]=useState<Quote|null>(null),[order,setOrder]=useState<Order|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState("");
 async function auth(json=false):Promise<Record<string,string>>{const t=await getAccessToken();if(!t)throw new Error("Your session expired. Sign in again.");return json?{Authorization:"Bearer "+t,"Content-Type":"application/json"}:{Authorization:"Bearer "+t}}
 useEffect(()=>{if(!walletReady)return;let cancelled=false;void(async()=>{try{const r=await fetch("/api/funding/institutions",{headers:await auth()}),j=await r.json();if(r.ok&&!cancelled)setBanks(Array.isArray(j.institutions)?j.institutions:[])}catch{}})();return()=>{cancelled=true}},[walletReady]);
 async function getQuote(){setError("");setQuote(null);const n=Number(amount);if(!Number.isFinite(n)||n<=0)return setError("Enter how much Naira you want to transfer.");setBusy(true);try{const r=await fetch("/api/funding/quote",{method:"POST",headers:await auth(true),body:JSON.stringify({currency:"NGN",amountNgn:n})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not get quote");setQuote({amount_ngn:Number(j.amount_ngn),amount_usdc:Number(j.amount_usdc)})}catch(e){const msg=e instanceof Error?e.message:"Could not get quote";setError(/onramp access|request access|doesn.t have onramp/i.test(msg)?"Naira funding is not enabled for Tab yet. We’ve wired the flow and are waiting for MiniSend to enable on-ramp access.":msg)}finally{setBusy(false)}}
 async function createOrder(){setError("");if(!bank)return setError("Choose the bank account you want refunds sent to.");if(!/^\d{10}$/.test(account))return setError("Enter your 10-digit bank account number.");setBusy(true);try{const r=await fetch("/api/funding/orders",{method:"POST",headers:await auth(true),body:JSON.stringify({currency:"NGN",amountNgn:Number(amount),institution:bank,accountNumber:account,})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not create bank transfer");setOrder(j as Order)}catch(e){setError(e instanceof Error?e.message:"Could not create bank transfer")}finally{setBusy(false)}}
 async function refresh(){if(!order)return;setBusy(true);setError("");try{const r=await fetch("/api/funding/orders?orderId="+encodeURIComponent(order.orderId),{headers:await auth()}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not check transfer");setOrder(o=>o?{...o,...j}:j)}catch(e){setError(e instanceof Error?e.message:"Could not check transfer")}finally{setBusy(false)}}
 async function copy(v:string,key:string){await navigator.clipboard.writeText(v);setCopied(key);setTimeout(()=>setCopied(""),1200)}
 if(!walletReady)return <div className="walletRouteDetail"><b>Fund with Naira</b><p>Your permanent Tab Wallet needs to exist first. It receives the USDC after your bank transfer is confirmed.</p><button className="walletRoutePrimary" onClick={()=>void onWalletNeeded()}>Create Tab Wallet</button></div>;
 if(order){const pi=order.paymentInstructions;return <div className="walletRouteDetail"><b>Bank transfer created</b><p>{order.status==="deposit_received"?"We received your Naira. MiniSend is releasing your USDC now.":order.status==="completed"||order.status==="released"?"Funding completed.":order.status==="failed"?"This funding attempt failed. Do not pay again if you already transferred.":order.status==="expired"?"This bank account has expired. Create a new funding request to try again.":"Transfer the exact amount below before the account expires."}</p>{pi&&order.status==="pending"&&<div className="fundingAddressCard"><small>Transfer exactly</small><code>₦{pi.amount}</code><button onClick={()=>copy(pi.amount,"amount")}>{copied==="amount"?"Copied":"Copy amount"}</button><small>{pi.bank_name}</small><code>{pi.account_number}</code><button onClick={()=>copy(pi.account_number,"account")}>{copied==="account"?"Copied":"Copy account"}</button><small>Account name</small><b>{pi.account_name}</b><small>Expires {new Date(pi.expires_at).toLocaleString()}</small></div>}{order.refundAccount?.account_name&&<div className="baseFundingDisclosure"><b>{order.refundAccount.account_name}</b><small>Verified refund account name</small></div>}<div className="baseFundingDisclosure"><b>{order.amountUsdc?Number(order.amountUsdc).toLocaleString(undefined,{maximumFractionDigits:6})+" USDC":"USDC"} to your Tab Wallet</b><small>MiniSend releases the USDC on Base to your permanent Tab Wallet. Your configured settlement can then consolidate supported deposits to Arc.</small></div>{order.releaseTxHash&&<div className="baseFundingDisclosure"><b>USDC released ✓</b><small>{order.releaseTxHash}</small></div>}{order.failureReason&&<div className="error">{order.failureReason==="deposit_not_settled"?"Your Naira was received but settlement needs MiniSend support. Do not transfer again.":"Funding failed: "+order.failureReason}</div>}<button className="walletRoutePrimary" disabled={busy} onClick={refresh}>{busy?"Checking…":"Check status"}</button></div>}
 return <div className="walletRouteDetail"><b>Fund with Naira</b><p>Transfer NGN from your Nigerian bank account and receive USDC in your Tab Wallet.</p><label>Amount to transfer (NGN)<input inputMode="decimal" value={amount} onChange={e=>{setAmount(e.target.value);setQuote(null)}} placeholder="10000"/></label>{!quote?<button className="walletRoutePrimary" disabled={busy} onClick={getQuote}>{busy?"Getting quote…":"Get live quote"}</button>:<><div className="baseFundingDisclosure"><b>₦{quote.amount_ngn.toLocaleString()} → {quote.amount_usdc.toLocaleString(undefined,{maximumFractionDigits:6})} USDC</b><small>This is a live quote. MiniSend prices the final order again when the bank account is created.</small></div><label>Refund bank<select value={bank} onChange={e=>setBank(e.target.value)}><option value="">Choose bank</option>{banks.map((x,i)=>{const code=x.code||x.institution||"";return <option key={code||String(i)} value={code}>{x.name||x.bank_name||code}</option>})}</select></label><label>Your 10-digit account number<input inputMode="numeric" maxLength={10} value={account} onChange={e=>setAccount(e.target.value.replace(/\D/g,"").slice(0,10))} placeholder="0123456789"/></label><div className="baseFundingDisclosure"><b>Account name is checked automatically</b><small>MiniSend verifies the bank account and uses the registered account name when the transfer request is created.</small></div><small>This account is used only if MiniSend needs to refund your Naira after payment.</small><button className="walletRoutePrimary" disabled={busy||banks.length===0} onClick={createOrder}>{busy?"Creating account…":"Create bank transfer"}</button></>}{error&&<p className="error">{error}</p>}</div>
}
