import{NextResponse}from"next/server";import{desc,eq,or}from"drizzle-orm";import{currentUser}from"@/lib/current-user";import{getDb}from"@/lib/db";import{settlements,tabs,tabWallets,users,walletDeposits,fundingOrders}from"@/db/schema";import{resolveStoredTabWallet}from"@/lib/resolve-tab-wallet";import{listWalletTransfers}from"@/lib/minisend-wallet";import{getOnrampOrder}from"@/lib/funding/minisend";
function statusOf(state:string){const s=String(state||"").toLowerCase();if(s==="completed"||s==="complete"||s==="settled"||s==="released")return"success";if(s==="failed")return"failed";if(s==="reversed"||s==="refunded")return"reversed";if(s==="under_review")return"review";return"pending"}
export async function GET(){try{const u=await currentUser(),db=getDb();const[legacy,ownWallet,knownWallets,deposits,funding]=await Promise.all([
 db.select({id:settlements.id,tabId:settlements.tabId,tabName:tabs.name,fromUserId:settlements.fromUserId,toUserId:settlements.toUserId,amountUsdc:settlements.amountUsdc,arcTxHash:settlements.arcTxHash,settledAt:settlements.settledAt}).from(settlements).innerJoin(tabs,eq(settlements.tabId,tabs.id)).where(or(eq(settlements.fromUserId,u.id),eq(settlements.toUserId,u.id))),
 resolveStoredTabWallet(u),
 db.select({walletRef:tabWallets.walletRef,userId:users.id,name:users.name,email:users.email}).from(tabWallets).innerJoin(users,eq(tabWallets.userId,users.id)),
 db.select().from(walletDeposits).where(eq(walletDeposits.userId,u.id)).orderBy(desc(walletDeposits.receivedAt)).limit(50),
 db.select().from(fundingOrders).where(eq(fundingOrders.userId,u.id)).orderBy(desc(fundingOrders.createdAt)).limit(50)
 ]);
 const refreshedFunding=await Promise.all(funding.map(async row=>{if(!row.providerOrderId||["completed","released","failed","expired"].includes(String(row.status)))return row;try{const live=await getOnrampOrder(row.providerOrderId);const providerStatus=String(live.status||row.status);const nextStatus=live.release_tx_hash||["completed","released","success"].includes(providerStatus)?"completed":providerStatus==="failed"?"failed":providerStatus==="expired"?"expired":"pending";await db.update(fundingOrders).set({status:nextStatus as any,amountLocal:live.amount_local!=null?String(live.amount_local):row.amountLocal,feeLocal:live.fee!=null?String(live.fee):row.feeLocal,amountUsdc:live.amount_usdc!=null?String(live.amount_usdc):row.amountUsdc,rate:live.rate!=null?String(live.rate):row.rate,releaseTxHash:live.release_tx_hash??row.releaseTxHash,failureReason:live.failure_reason??row.failureReason,updatedAt:new Date()}).where(eq(fundingOrders.id,row.id));return{...row,status:nextStatus,amountLocal:live.amount_local!=null?String(live.amount_local):row.amountLocal,feeLocal:live.fee!=null?String(live.fee):row.feeLocal,amountUsdc:live.amount_usdc!=null?String(live.amount_usdc):row.amountUsdc,rate:live.rate!=null?String(live.rate):row.rate,releaseTxHash:live.release_tx_hash??row.releaseTxHash,failureReason:live.failure_reason??row.failureReason}}catch(e){console.error("Funding status reconciliation failed",row.id,e);return row}}));
 const nameByRef=new Map(knownWallets.map(x=>[x.walletRef,{name:x.name,email:x.email,userId:x.userId}]));
 let providerTransfers:any[]=[];if(ownWallet){try{const result=await listWalletTransfers(100,0);providerTransfers=(result.transfers||[]).filter(x=>x.from===ownWallet.walletRef||x.to===ownWallet.walletRef)}catch(e){console.error("MiniSend transfer history unavailable",e)}}
 const transferTx=providerTransfers.map(x=>{const direction=x.from===ownWallet?.walletRef?"sent":"received",otherRef=direction==="sent"?x.to:x.from,other=nameByRef.get(otherRef);return{id:x.id,source:"wallet_transfer",title:direction==="sent"?`Sent to ${other?.name||"Tab user"}`:`Received from ${other?.name||"Tab user"}`,direction,counterpartyName:other?.name||"Tab user",counterpartyEmail:other?.email||null,amountUsdc:String(x.amount),asset:x.token||"USDC",status:statusOf(x.state),providerState:x.state,txHash:x.tx_hash||null,createdAt:x.created_at||x.updated_at||new Date().toISOString(),tabId:null}});
 const legacyTx=legacy.filter(x=>x.arcTxHash||x.settledAt).map(x=>({id:x.id,source:"tab_settlement",title:x.tabName,direction:x.fromUserId===u.id?"sent":"received",counterpartyName:null,counterpartyEmail:null,amountUsdc:String(x.amountUsdc),asset:"USDC",status:x.arcTxHash&&x.settledAt?"success":"pending",providerState:x.arcTxHash&&x.settledAt?"completed":"pending",txHash:x.arcTxHash||null,createdAt:x.settledAt?.toISOString()||new Date().toISOString(),tabId:x.tabId}));
 const depositTx=deposits.map(x=>({id:x.id,source:"crypto_funding",title:"Wallet funding",direction:"received",counterpartyName:null,counterpartyEmail:null,amountUsdc:String(x.settlementAmount||x.amount),asset:x.token||"USDC",status:statusOf(x.settlementStatus||x.status),providerState:x.settlementStatus||x.status,txHash:x.settlementTxHash||x.txHash||null,createdAt:x.receivedAt.toISOString(),tabId:null}));
 const fundingTx=refreshedFunding.map(x=>({id:x.id,source:String(x.currency||"").toUpperCase()==="NGN"?"naira_funding":"fiat_funding",title:String(x.currency||"").toUpperCase()==="NGN"?"Funded with Naira":"Wallet funding",direction:"received",counterpartyName:null,counterpartyEmail:null,amountUsdc:String(x.amountUsdc),asset:"USDC",status:statusOf(x.status),providerState:x.status,txHash:x.releaseTxHash||null,createdAt:x.createdAt.toISOString(),tabId:null,amountLocal:x.amountLocal?String(x.amountLocal):null,localCurrency:x.currency||null,reference:x.externalReference}));
 const seenFundingRefs=new Set(fundingTx.map(x=>x.txHash).filter(Boolean));const dedupedDeposits=depositTx.filter(x=>!x.txHash||!seenFundingRefs.has(x.txHash));
 const transactions=[...transferTx,...legacyTx,...fundingTx,...dedupedDeposits].sort((a,b)=>+new Date(b.createdAt)-+new Date(a.createdAt));return NextResponse.json({transactions,settlements:transactions})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:"Unable to load transaction history"},{status:400})}}
